//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace crud.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class staff
    {
        [DisplayName("No")]
        public int id { get; set; }


        [Required]
        [DisplayName("Name")]
        [RegularExpression(@"^[a-zA-Z ]+$", ErrorMessage = "Use letters only please")]
        [StringLength(maximumLength: 50, ErrorMessage = "Limited at 50 characters")]
        public string name { get; set; }


        [Required]
        [DisplayName("Email")]
        [EmailAddress(ErrorMessage = "Invalid Email Address")]
        [StringLength(maximumLength: 50, ErrorMessage = "Limited at 50 characters")]
        public string email { get; set; }


        [Required]
        [DisplayName("Address")]
        [RegularExpression(@"^[a-zA-Z0-9,/\:;. ]+$", ErrorMessage = "Not allow special character")]
        [StringLength(maximumLength: 150, ErrorMessage = "Limited at 50 characters")]
        public string address { get; set; }

        [Required]
        [DisplayName("Phone")]
        [RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Invalid Phone number")]
        public string phone { get; set; }
    }
}
